"""Add user suspension and admin controls v3

Revision ID: 0acdfd38585a
Revises: 40b58f44ceae
Create Date: 2025-08-29 02:06:02.894076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acdfd38585a'
down_revision = '40b58f44ceae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suspension_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('suspended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('suspended_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_views')
        batch_op.drop_column('last_login')
        batch_op.drop_column('suspended_by_id')
        batch_op.drop_column('suspended_at')
        batch_op.drop_column('suspension_reason')
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
