"""enhance appointment system with tracking

Revision ID: 20251010_024908
Revises: 753be8e0e744
Create Date: 2025-01-10 02:49:08.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251010_024908'
down_revision = '753be8e0e744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('internal_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('follow_up_required')
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('internal_notes')
        batch_op.drop_column('feedback')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###