"""Enhanced CardView model with analytics fields

Revision ID: 27211d15a785
Revises: a66ae6ff1ecd
Create Date: 2025-08-30 15:09:25.620336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27211d15a785'
down_revision = 'a66ae6ff1ecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('browser', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_view', schema=None) as batch_op:
        batch_op.drop_column('session_id')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('platform')
        batch_op.drop_column('browser')
        batch_op.drop_column('device_type')

    # ### end Alembic commands ###
