"""Add image_path to Service model

Revision ID: 3d1608713d3f
Revises: fd6bad72e9b6
Create Date: 2025-08-27 23:17:40.406342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1608713d3f'
down_revision = 'fd6bad72e9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
