"""Add rectangle avatar shape option

Revision ID: 40b58f44ceae
Revises: 6a67c37c6bda
Create Date: 2025-08-29 01:35:12.431308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b58f44ceae'
down_revision = '6a67c37c6bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('avatar_shape',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('circle', 'rounded', 'square', 'rectangle', name='avatar_shapes'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('avatar_shape',
               existing_type=sa.Enum('circle', 'rounded', 'square', 'rectangle', name='avatar_shapes'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)

    # ### end Alembic commands ###
