"""Add appointment system pause and phone prefix features

Revision ID: 753be8e0e744
Revises: f90c3a486501
Create Date: 2025-10-02 21:53:09.480210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753be8e0e744'
down_revision = 'f90c3a486501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_phone_country', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('patient_birthdate', sa.Date(), nullable=True))

    with op.batch_alter_table('appointment_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepting_appointments', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('pause_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resume_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_country_prefix', sa.String(length=10), nullable=True, server_default='+52'))
        batch_op.add_column(sa.Column('require_patient_phone', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('require_patient_email', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('collect_patient_birthdate', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_system', schema=None) as batch_op:
        batch_op.drop_column('collect_patient_birthdate')
        batch_op.drop_column('require_patient_email')
        batch_op.drop_column('require_patient_phone')
        batch_op.drop_column('phone_country_prefix')
        batch_op.drop_column('resume_time')
        batch_op.drop_column('pause_message')
        batch_op.drop_column('is_accepting_appointments')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('patient_birthdate')
        batch_op.drop_column('patient_phone_country')

    # ### end Alembic commands ###
