"""Add custom_layout field to Card model for visual editor

Revision ID: 84cb581ef2df
Revises: 27211d15a785
Create Date: 2025-08-30 18:01:02.950415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cb581ef2df'
down_revision = '27211d15a785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_layout', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('custom_layout')

    # ### end Alembic commands ###
