"""Add avatar_square_path and avatar_rect_path to Card model

Revision ID: 893b26571bd9
Revises: e296cf7965be
Create Date: 2025-08-30 03:31:54.283919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893b26571bd9'
down_revision = 'e296cf7965be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_square_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar_rect_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('avatar_rect_path')
        batch_op.drop_column('avatar_square_path')

    # ### end Alembic commands ###
