"""Add additional social media fields

Revision ID: a091f279a26a
Revises: f7fe1d8c99b0
Create Date: 2025-08-27 16:22:47.837893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a091f279a26a'
down_revision = 'f7fe1d8c99b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('telegram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snapchat', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pinterest', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('behance', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dribbble', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('dribbble')
        batch_op.drop_column('behance')
        batch_op.drop_column('github')
        batch_op.drop_column('pinterest')
        batch_op.drop_column('snapchat')
        batch_op.drop_column('telegram')
        batch_op.drop_column('tiktok')
        batch_op.drop_column('youtube')
        batch_op.drop_column('twitter')

    # ### end Alembic commands ###
