"""Add ticket system improvements: priority, check-in, medical notes, notifications config

Revision ID: a2cb20548e38
Revises: 2ff205a4198a
Create Date: 2025-10-10 00:30:51.758825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cb20548e38'
down_revision = '2ff205a4198a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_checked_in', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('medical_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_token', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ticket_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_new_ticket', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('notify_long_wait', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('long_wait_threshold', sa.Integer(), nullable=False, server_default='60'))
        batch_op.add_column(sa.Column('send_whatsapp_reminders', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reminder_threshold', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('target_service_time', sa.Integer(), nullable=False, server_default='20'))
        batch_op.add_column(sa.Column('enable_sound_alerts', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_system', schema=None) as batch_op:
        batch_op.drop_column('enable_sound_alerts')
        batch_op.drop_column('target_service_time')
        batch_op.drop_column('reminder_threshold')
        batch_op.drop_column('send_whatsapp_reminders')
        batch_op.drop_column('long_wait_threshold')
        batch_op.drop_column('notify_long_wait')
        batch_op.drop_column('notify_new_ticket')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('cancellation_token')
        batch_op.drop_column('medical_notes')
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('is_checked_in')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
