"""Add social network display preferences to Card model

Revision ID: ae47849c08ec
Revises: d728a5c5144e
Create Date: 2025-09-04 00:35:06.151477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47849c08ec'
down_revision = 'd728a5c5144e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_social_networks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('primary_social_networks')

    # ### end Alembic commands ###
