"""Add whatsapp_country field to Card model

Revision ID: b7d2535876fe
Revises: 893b26571bd9
Create Date: 2025-08-30 04:11:21.806780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d2535876fe'
down_revision = '893b26571bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_country', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_country')

    # ### end Alembic commands ###
