"""Add mobile_token to User

Revision ID: c3d986682e2a
Revises: a2cb20548e38
Create Date: 2026-02-27 21:02:50.856327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d986682e2a'
down_revision = 'a2cb20548e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_token', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_mobile_token'), ['mobile_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mobile_token'))
        batch_op.drop_column('mobile_token')

    # ### end Alembic commands ###
