"""Rename appointment system to ticket system

Revision ID: f409377e5def
Revises: 753be8e0e744
Create Date: 2025-10-07 02:26:33.434635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f409377e5def'
down_revision = '753be8e0e744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=200), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='unique_user_endpoint')
    )
    op.create_table('ticket_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('business_hours', sa.String(length=500), nullable=True),
    sa.Column('max_ticket_types', sa.Integer(), nullable=True),
    sa.Column('display_mode', sa.Enum('simple', 'detailed', name='display_modes'), nullable=True),
    sa.Column('is_accepting_tickets', sa.Boolean(), nullable=False),
    sa.Column('pause_message', sa.Text(), nullable=True),
    sa.Column('resume_time', sa.String(length=100), nullable=True),
    sa.Column('phone_country_prefix', sa.String(length=10), nullable=True),
    sa.Column('require_patient_phone', sa.Boolean(), nullable=False),
    sa.Column('require_patient_email', sa.Boolean(), nullable=False),
    sa.Column('collect_patient_birthdate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ticket_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_system_id'], ['ticket_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_system_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_phone_country', sa.String(length=10), nullable=True),
    sa.Column('patient_phone', sa.String(length=20), nullable=True),
    sa.Column('patient_email', sa.String(length=120), nullable=True),
    sa.Column('patient_birthdate', sa.Date(), nullable=True),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'completed', 'cancelled', 'no_show', name='ticket_statuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ticket_system_id'], ['ticket_system.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_ticket_number'), ['ticket_number'], unique=False)

    op.drop_table('appointment_system')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_created_at'))
        batch_op.drop_index(batch_op.f('ix_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_ticket_number'))

    op.drop_table('appointment')
    op.drop_table('appointment_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_system_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('estimated_duration', sa.INTEGER(), nullable=True),
    sa.Column('prefix', sa.VARCHAR(length=5), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('order_index', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_system_id'], ['appointment_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_system_id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_type_id', sa.INTEGER(), nullable=False),
    sa.Column('patient_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('patient_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('patient_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('ticket_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('called_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('cancellation_reason', sa.VARCHAR(length=500), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=True),
    sa.Column('patient_phone_country', sa.VARCHAR(length=10), nullable=True),
    sa.Column('patient_birthdate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_system_id'], ['appointment_system.id'], ),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_ticket_number'), ['ticket_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_created_at'), ['created_at'], unique=False)

    op.create_table('appointment_system',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('welcome_message', sa.TEXT(), nullable=True),
    sa.Column('business_hours', sa.VARCHAR(length=500), nullable=True),
    sa.Column('max_appointment_types', sa.INTEGER(), nullable=True),
    sa.Column('display_mode', sa.VARCHAR(length=8), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_accepting_appointments', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('pause_message', sa.TEXT(), nullable=True),
    sa.Column('resume_time', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_country_prefix', sa.VARCHAR(length=10), server_default=sa.text("'+52'"), nullable=True),
    sa.Column('require_patient_phone', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('require_patient_email', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('collect_patient_birthdate', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_created_at'))

    op.drop_table('ticket')
    op.drop_table('ticket_type')
    op.drop_table('ticket_system')
    op.drop_table('push_subscription')
    # ### end Alembic commands ###
