"""Add appointment system for medical appointments

Revision ID: f90c3a486501
Revises: 70dc817aa51c
Create Date: 2025-10-01 20:03:12.148693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90c3a486501'
down_revision = '70dc817aa51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('business_hours', sa.String(length=500), nullable=True),
    sa.Column('max_appointment_types', sa.Integer(), nullable=True),
    sa.Column('display_mode', sa.Enum('simple', 'detailed', name='display_modes'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_system_id'], ['appointment_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_system_id', sa.Integer(), nullable=False),
    sa.Column('appointment_type_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_phone', sa.String(length=20), nullable=True),
    sa.Column('patient_email', sa.String(length=120), nullable=True),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'completed', 'cancelled', 'no_show', name='appointment_statuses'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['appointment_system_id'], ['appointment_system.id'], ),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_ticket_number'), ['ticket_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_created_at'))

    op.drop_table('appointment')
    op.drop_table('appointment_type')
    op.drop_table('appointment_system')
    # ### end Alembic commands ###
