"""Add category, duration, is_featured and availability to Service model

Revision ID: fab9e2c033e5
Revises: 3d1608713d3f
Create Date: 2025-08-28 00:08:12.721341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab9e2c033e5'
down_revision = '3d1608713d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('availability', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('availability')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
