"""empty message

Revision ID: fd6bad72e9b6
Revises: a091f279a26a
Create Date: 2025-08-27 23:01:27.737294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6bad72e9b6'
down_revision = 'a091f279a26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_view_viewed_at'), ['viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_view_viewed_at'))

    op.drop_table('card_view')
    # ### end Alembic commands ###
